### ISSUE TITLE
Using SystemGlobal.objects.set does not save key:value to DB

### ISSUE THREAD

**Issue by pkarp0** [andres-torres-marroquin/django-system-globals#4]
Using Django 1.6.1
I have submitted a pull request for this issue.

The manager set() method does not save key:value to DB. It is only cached and is cleared at cache timeout. This behavior is unexpected. 

from system_globals.models import SystemGlobal
SystemGlobal.objects.set('key', 'value')
SystemGlobal.objects.all()
[]
SystemGlobal.objects.as_dict()
{'key': 'value'}

SystemGlobal.objects.create(var_name='hello', value='world')
SystemGlobal.objects.all()
[<SystemGlobal: hello = world>]
SystemGlobal.objects.as_dict()
{'hello': 'world', 'key': 'value'}

This can be fixed in the manager set() method:
    def set(self, var_name, value):
        """
        Make a atomic query for set a new value for a existent SystemGlobal, or
        create the new variable and set the new value.
        """
        updated_rows = self.filter(var_name=var_name).update(value=value)
        if not updated_rows:
            self.create(var_name=var_name, value=value)

        self._update_cache(var_name, value)

**Comment by pahko** [comment]
this was fixed in here: https://github.com/andres-torres-marroquin/django-system-globals/pull/7
